import type { Metadata } from 'next';
import './globals.css';
import '@repo/ui/styles.css';
import ScrollToTop from '@/components/scroll-to-top';

export const metadata: Metadata = {
  title: {
    template: '%s | App',
    default: 'App',
  },
  // description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <ScrollToTop />
      </body>
    </html>
  );
}
